module.exports = {
  rules: {
    'array-bracket-newline': ['error', 'consistent'],
    'array-bracket-spacing': ['error'],
    'array-element-newline': ['error', 'consistent'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'arrow-spacing': ['error'],
    'block-spacing': ['error'],
    'brace-style': ['error'],
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error'],
    'comma-style': ['error'],
    'computed-property-spacing': ['error'],
    'curly': ['error'],
    'dot-location': ['error', 'property'],
    'dot-notation': ['error'],
    'eol-last': ['error'],
    'eqeqeq': ['error', 'smart'],
    'func-call-spacing': ['error'],
    'function-paren-newline': ['error'],
    'generator-star-spacing': ['error', { before: false, after: true }],
    'indent': ['error', 2],
    'key-spacing': ['error'],
    'keyword-spacing': ['error'],
    'linebreak-style': ['error', 'unix'],
    'lines-between-class-members': ['error'],
    'multiline-ternary': ['error'],
    'new-parens': ['error', 'never'],
    'newline-per-chained-call': ['error', { ignoreChainWithDepth: 3 }],
    'no-div-regex': ['error'],
    'no-else-return': ['error'],
    'no-extra-bind': ['error'],
    'no-extra-boolean-cast': ['error'],
    'no-extra-parens': ['error', 'all', { nestedBinaryExpressions: false }],
    'no-extra-semi': ['error'],
    'no-floating-decimal': ['error'],
    'no-multi-spaces': ['error', { ignoreEOLComments: true }],
    'no-multiple-empty-lines': ['error', { max: 2, maxBOF: 0, maxEOF: 0 }],
    'no-trailing-spaces': ['error'],
    'no-undef-init': ['error'],
    'no-unneeded-ternary': ['error'],
    'no-unused-labels': ['error'],
    'no-useless-catch': ['error'],
    'no-useless-rename': ['error'],
    'no-useless-return': ['error'],
    'no-var': ['error'],
    'no-whitespace-before-property': ['error'],
    'object-curly-newline': ['error', { multiline: true }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'object-shorthand': ['error'],
    'one-var': ['error', 'never'],
    'operator-assignment': ['error'],
    'operator-linebreak': ['error', 'after'],
    'padded-blocks': ['error', 'never'],
    'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
    'prefer-destructuring': ['error'],
    'prefer-exponentiation-operator': ['error'],
    'prefer-numeric-literals': ['error'],
    'prefer-object-has-own': ['error'],
    'prefer-object-spread': ['error'],
    'prefer-template': ['error'],
    'quote-props': ['error', 'consistent-as-needed'],
    'quotes': ['error', 'single'],
    'rest-spread-spacing': ['error'],
    'semi': ['error', 'never'],
    'semi-spacing': ['error'],
    'sort-imports': ['error'],
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': ['error'],
    'space-unary-ops': ['error'],
    'switch-colon-spacing': ['error'],
    'template-curly-spacing': ['error', 'never'],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': ['error', 'never'],
    'wrap-iife': ['error', 'inside'],
    'yield-star-spacing': ['error', { before: false, after: true }],
  }
}
